apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: on4l5crsr-go 
  janus-idp.io/tekton: on4l5crsr-go
  backstage.io/kubernetes-id: on4l5crsr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: on4l5crsr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml